version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      APP_NAME: MyFlaskApp
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: Meta@123
      MYSQL_DB: geeklogin
    expose:
      - 8080

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Meta@123
      MYSQL_DATABASE: geeklogin
    volumes:
      - mysqldir:/var/lib/mysql
      - dump:/docker-entrypoint-initdb.d

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

volumes:
  mysqldir:
  dump: